module ApplicationHelper
  def get_all_cities
    ['Karachi',
    'Lahore',
    'Faisalabad',
    'Rawalpindi',
    'Multan',
    'Gujranwala',
    'Hyderabad',
    'Peshawar',
    'Islamabad',
    'Quetta',
    'Sargodha',
    'Sialkot',
    'Bahawalpur',
    'Sukkur',
    'Jhang',
    'Shekhupura',
    'Mardan',
    'Gujrat',
    'Larkana',
    'Kasur',
    'Rahim Yar Khan',
    'Sahiwal',
    'Okara',
    'Wah Cantonment',
    'Dera Ghazi Khan',
    'Mingora',
    'Mirpur Khas',
    'Chiniot',
    'Nawabshah',
    'Kamoke',
    'Burewala',
    'Jhelum',
    'Sadiqabad',
    'Khanewal',
    'Hafizabad',
    'Kohat',
    'Jacobabad',
    'Shikarpur',
    'Muzaffargarh',
    'Khanpur',
    'Gojra',
    'Bahawalnagar',
    'Abbottabad',
    'Muridke',
    'Pakpattan',
    'Khuzdar',
    'Jaranwala',
    'Chishtian',
    'Daska',
    'Mandi Bahauddin',
    'Ahmadpur East',
    'Kamalia',
    'Tando Adam',
    'Khairpur',
    'Dera Ismail Khan',
    'Vehari',
    'Nowshera',
    'Dadu',
    'Wazirabad',
    'Khushab',
    'Charsada',
    'Swabi',
    'Chakwal',
    'Mianwali',
    'Tando Allahyar',
    'Kot Adu',
    'Turbat']
  end
  
  def get_all_categories
    ['Accounting & Finance',
    'Hospital',
    'Advertising & Marketing',
    'Service Centers',
    'Automotive',
    'Retail stores',
    'Education',
    'Franchises',
    'Agriculture',
    'Moving & Storage',
    'Manufacturing',
    'Printing',
    'Trading',
    'Entertainment centers']
  end
end
